spring:
  profiles:
    active: dev

qiniu:
  accessKey:  WXhIUPvw7NDPzARNo5a2zNMzg2EakC_dx5MAJYWq
  secretKey:  X918sxCOfJzhTTUrlYWBfeHFIxOAWp0kBPn-_zAo
  bucket: business

#######redis配置#######
redis:
  ip: 116.62.49.63
  port: 6379
  password: ddm201606
  max:
    total:  20
    idle: 10
  min:
    idle: 2
  test:
    borrow: true
    return: true


