package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    Cart selectCartByUserIdAndProductId(@Param("userId")Integer userId,
                                        @Param("productId")Integer productId);

    List<Cart> selectCartByUserId(Integer userId);

    /*
    * 是否全选
    * */
    int isCheckedAll(Integer userId);

    int deleteByUserIdAndProductIds(@Param("userId")Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);

    /*
    * 操作购物车商品是否选中
    * */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("check")Integer check);

    int get_cart_product_count(Integer userId);

    List<Cart> findCartListByUserIdChecked(Integer userId);

    /*
    * 批量删除购物车商品
    * */
    int batchDelete(List<Cart> cartList);
}