package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);


    /*判断用户名是否存在*/
    int exsistUsername(@Param("username") String username);
    int exsistEmail(@Param("email")String email);
    UserInfo selectByUsernameAdPassword(@Param("username")String username,
                                        @Param("password")String password);

    String selectQuestionByUsername(String username);

    int selectByUsernameAdQuestionAndAnswer(@Param("username")String username,
                                            @Param("question")String question,
                                            @Param("answer")String answer);

    int updateUserPasswordByUsername(@Param("username") String username,@Param("password")String newpassword);

    int updateUserBySelectActive(UserInfo userInfo);
}